openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        image_name:
          title: 镜像名
          type: string
          description: Name for the log server image
          default: redis-by-terraform
          x-walrus-ui:
            group: Basic
            order: 2
        image_url:
          title: 镜像 Url
          type: string
          description: URL to download the image from
          default: http://minio.zstack.io:9000/packer/redis-by-packer-image-compressed.qcow2
          x-walrus-ui:
            group: Basic
            order: 3
        backup_storage_name:
          title: 镜像服务器
          type: string
          description: Name of the backup storage to use
          default: bs
          x-walrus-ui:
            group: Basic
            order: 4
        instance_name:
          title: 云主机名称
          type: string
          description: Name for the cas server instance
          default: redis
          x-walrus-ui:
            group: Basic
            order: 5
        l3_network_name:
          title: 三层网络名称
          type: string
          description: Name of the L3 network to use
          default: test
          x-walrus-ui:
            group: Basic
            order: 6
        instance_offering_name:
          title: 计算规格名称
          type: string
          description: Name of the instance offering to use
          default: min
          x-walrus-ui:
            group: Basic
            order: 7
        ssh_user:
          title: Ssh User
          type: string
          description: SSH username for remote access
          default: root
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 8
        ssh_password:
          title: Ssh Password
          type: string
          description: SSH password for remote access
          default: password
          format: password
          readOnly: true
          x-walrus-ui:
            group: Basic
            order: 9
        redis_password:
          title: Redis Password
          type: string
          description: SSH password for remote access
          default: zstack.redis.password
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 10
        non_production:
          title: 是否为生产环境
          type: boolean
          description: Whether to run in non-production mode
          default: false
          x-walrus-ui:
            group: Basic
            order: 10
        architecture:
          title: Redis架构
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: replication
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 11
        expunge:
          title: 是否彻底删除
          type: boolean
          default: true
          x-walrus-ui:
            group: Basic
            order: 13
      x-walrus-ui:
        groupOrder:
        - Basic
